config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'   
  resources :bubbles
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get  '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  match '/signup',  to: 'users#new', via: 'get' 
  match '/help',    to: 'static_pages#help',    via: 'get'
  post 'users/create'
  resources :users 
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/404.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>404 page</title>
</head>
<body>
	<div class="page-not-found">
		<h1>404</h1>
	</div>

	<p id="help">Hay lien he voi chung toi <strong>Chung toi se ho tro cac ban.</strong></p>
</body>
</html>

app/views/static_pages/contact.html.erb
	
<!DOCTYPE HTML>
<html>
<head>
	<title>FramGia Company</title>
	<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link href='http://fonts.googleapis.com/css?family=Playball' rel='stylesheet' type='text/css'>   
</head>
<body>
	<div class="header-bg">
		<div class="wrap"> 
			<div class="h-bg">
				<div class="total">
					<div class="header">
						<div class="header-right">
							<ul class="follow_icon">
								<li><a href="#"><%= image_tag("image/co-nb.png", :alt => "rss feed") %></a></li>
								<li><a href="#"><%= image_tag("image/lo-pn.png", :alt => "rss feed") %></a></li>
							</ul>
						</div><div class="clear"></div> 
						<div class="header-bot">
							<div class="logo">
								<a href="#">
									<%= image_tag("image/logo.png") %>
								</a>
							</div>
							<div class="search">
								<input type="text" class="textbox" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}">
								<button class="gray-button"><span>Search</span></button>
							</div>
							<div class="clear"></div> 
						</div>		
					</div>	
					<div class="menu"> 	
						<div class="top-nav"> 
							<ul>
								<li class="#"><a href="index.html">Trang Chủ</a></li>
								<li><a href="#">Danh mục Sản Phẩm</a></li>
								<li><a href="#">Khuyến Mãi</a></li>
								<li><a href="#">Liên hệ </a></li>
							</ul>
							<div class="clear"></div> 
						</div>
					</div>
					<div class="banner-top">
						<div class="header-bottom">
							<div class="header_bottom_right_images">
								<div class="about_wrapper"><h1>Thong tin Lien he</h1>
								</div>
								<div class="section group">
									<div class="col span_2_of_c">
										<div class="contact-form">
											<h3>Contact Us</h3>
											<form method="post" action="contact-post.html">
												<div>
													<span><label>NAME</label></span>
													<span><input name="userName" type="text" class="textbox"></span>
												</div>
												<div>
													<span><label>E-MAIL</label></span>
													<span><input name="userEmail" type="text" class="textbox"></span>
												</div>
												<div>
													<span><label>MOBILE</label></span>
													<span><input name="userPhone" type="text" class="textbox"></span>
												</div>
												<div>
													<span><label>SUBJECT</label></span>
													<span><textarea name="userMsg"> </textarea></span>
												</div>
												<div>
													<span><input type="submit" value="Submit"></span>
												</div>
											</form>
										</div>
									</div><div class="clear"></div>
								</div>
							</div>
						</div>
				  </div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/static_pages/help.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!</h1>
                <h2>
                    404 Not Found</h2>
                <div class="error-details">
                    Sorry, an error has occured, Requested page not found!
                </div>
                <div class="error-actions">
                    <a href="http://www.jquery2dotnet.com" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
                        Take Me Home </a><a href="http://www.jquery2dotnet.com" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-envelope"></span> Contact Support </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/home.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>FramGia Company</title>
		<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link href='http://fonts.googleapis.com/css?family=Playball' rel='stylesheet' type='text/css'>   
	<!--slider-->
	<script src="js/jquery.min.js"></script>
	<script src="js/script.js" type="text/javascript"></script>
	<script src="js/superfish.js"></script>
	</head>
<body>
<div class="header-bg">
	<div class="wrap"> 
		<div class="h-bg">
			<div class="total">
				<div class="header">
					<div class="header-right">
						<header class="navbar navbar-fixed-top navbar-inverse">
							  <div class="container">
							    <%= link_to "", root_path, id: "logo" %>
							    <nav>
							      <ul class="nav navbar-nav navbar-right">
							        <li><%= link_to "Home", root_path %></li>
							        <li><%= link_to "Help", help_path %></li>
							        <% if logged_in? %>
							          <li><%= link_to "Users", '#' %></li>
							          <li class="dropdown">
							            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
							              Account <b class="caret"></b>
							            </a>
							            <ul class="dropdown-menu">
							              <li><%= link_to "Profile", current_user %></li>
							              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
							              <li class="divider"></li>
							              <li>
							                <%= link_to "Log out", logout_path, method: :delete %>
							              </li>
							            </ul>
							          </li>
							        <% else %>
							          <li><%= link_to "Log in", login_path %></li>
							        <% end %>
							      </ul>
							    </nav>
							  </div>
							</header>
					</div><div class="clear"></div> 
					<div class="header-bot">
						<div class="logo">
							<a href="index.html">
							<%= image_tag("image/logo.png") %>
							</a>
						</div>
						<div class="search">
						    <input type="text" class="textbox" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}">
						    <button class="gray-button"><span>Search</span></button>
				       </div>
					<div class="clear"></div> 
				</div>		
		</div>	
		<div class="menu"> 	
			<div class="top-nav"> 
					<ul>
						<li class="#"><a href="index.html">Trang Chủ</a></li>
						<li><a href="#">Danh mục Sản Phẩm</a></li>
						<li><a href="#">Khuyến Mãi</a></li>
						<li><a href="#">Liên hệ </a></li>
					</ul>
					<div class="clear"></div> 
				</div>
		</div>
		<div class="banner-top">
			<div class="header-bottom">
				 <div class="header_bottom_right_images">
		  			<div class="content-wrapper">		  
						<div class="content-top">
							  	<div class="box_wrapper"><h1>Sản Phẩm Mới nhất</h1>
								</div>
							 <div class="text"> 	
								<div class="grid_1_of_3 images_1_of_3">
									<div class="grid_1">
										<a href="single.html"><%= image_tag("image/sanpham.jpg") %></a>
											<div class="grid_desc">
												<p class="title">Quả Cầu Tuyết Thủy Tinh</p>
												<p class="title1">Chất liệu: thủy tinh, đá nhân tạo. - Kích thước: 15x10cm. - Thiết kế: có chức năng phát nhạc, trong quả cầu có ánh kim tạo hiệu ứng đẹp mắt.</p>
													 <div class="price" style="height: 19px;">
													 	 <span class="reducedfrom">$20.00</span>
								        				<span class="actual">$30.00</span>
													</div>
													<div class="cart-button">
														<div class="cart">
															<a href="#"><%= image_tag("demo/cart.png") %></a>
														</div>
														<button class="button"><span>Details</span></button>
													<div class="clear"></div>
												</div>
											</div>
								</div><div class="clear"></div>
							</div>
									<div class="grid_1_of_3 images_1_of_3">
										  <div class="grid_1">
										<a href="single.html"><%= image_tag("image/sanpham1.png") %></a>
											<div class="grid_desc">
												<p class="title">Quả cầu tuyết thiên sứ tình yêu</p>
												<p class="title1">Chất liệu: Quả cầu bằng thủy tinh dày. Đế bằng nhựa cao cấp. Các chi tiết được làm rất sắc nét. - Kích thước: 12x8cm. - Màu sắc: Màu trắng. Có những hạt kim tuyến óng ánh bên trong có thể bay lơ lửng tạo hiệu ứng đẹp mắt</p>
													 <div class="price" style="height: 19px;">
													 	 <span class="reducedfrom">$66.00</span>
								        				<span class="actual">$12.00</span>
													</div>
													<div class="cart-button">
														<div class="cart">
															<a href="#"><img src="images/cart.png" alt=""/></a>
														</div>
														<button class="button"><span>Details</span></button>
													<div class="clear"></div>
												</div>
											</div>
								</div><div class="clear"></div>
									</div>
									<div class="grid_1_of_3 images_1_of_3">
										  <div class="grid_1">
											<div class="grid_desc">
												<p class="title">Quả cầu tuyết cặp đôi tình yêu</p>
												<p class="title1">Chất liệu: thủy tinh, đá nhân tạo. - Kích thước: 15x10cm. - Thiết kế: có chức năng phát nhạc, trong quả cầu có ánh kim tạo hiệu ứng đẹp mắt. .</p>
													 <div class="price" style="height: 19px;">
													 	 <span class="reducedfrom">$66.00</span>
								        				<span class="actual">$12.00</span>
													</div>
													<div class="cart-button">
														<div class="cart">
															<a href="#"><img src="images/cart.png" alt=""/></a>
														</div>
														<button class="button"><span>Details</span></button>
													<div class="clear"></div>
												</div>
											</div>
								</div><div class="clear"></div>
									</div><div class="clear"></div>
								</div>
						</div>
						<div class="content-top">
							  	<div class="box_wrapper"><h1>Featured Products</h1>
								</div>
							 <div class="text"> 	
								<div class="grid_1_of_3 images_1_of_3">
									<div class="grid_1">
										<a href="single.html"><img src="images/pic1.jpg" title="continue reading" alt=""></a>
											<div class="grid_desc">
												<p class="title">Lorem ipsum dolor sitconsectetuer adipiscing elit</p>
												<p class="title1">Lorem ipsum dolor sitconsectetuer adipiscing elit</p>
													 <div class="price" style="height: 19px;">
													 	 <span class="reducedfrom">$66.00</span>
								        				<span class="actual">$12.00</span>
													</div>
													<div class="cart-button">
														<div class="cart">
															<a href="#"><img src="images/cart.png" alt=""/></a>
														</div>
														<button class="button"><span>Details</span></button>
													<div class="clear"></div>
												</div>
											</div>
								</div><div class="clear"></div>
							</div>
									<div class="grid_1_of_3 images_1_of_3">
										  <div class="grid_1">
										<a href="single.html"><img src="images/pic2.jpg" title="continue reading" alt=""></a>
											<div class="grid_desc">
												<p class="title">Lorem ipsum dolor sitconsectetuer adipiscing elit</p>
												<p class="title1">Lorem ipsum dolor sitconsectetuer adipiscing elit</p>
													 <div class="price" style="height: 19px;">
													 	 <span class="reducedfrom">$66.00</span>
								        				<span class="actual">$12.00</span>
													</div>
													<div class="cart-button">
														<div class="cart">
															<a href="#"><img src="images/cart.png" alt=""/></a>
														</div>
														<button class="button"><span>Details</span></button>
													<div class="clear"></div>
												</div>
											</div>
								</div><div class="clear"></div>
									</div>
									<div class="grid_1_of_3 images_1_of_3">
										  <div class="grid_1">
										<a href="single.html"><img src="images/pic3.jpg" title="continue reading" alt=""></a>
											<div class="grid_desc">
												<p class="title">Lorem ipsum dolor sitconsectetuer adipiscing elit</p>
												<p class="title1">Lorem ipsum dolor sitconsectetuer adipiscing elit</p>
													 <div class="price" style="height: 19px;">
													 	 <span class="reducedfrom">$66.00</span>
								        				<span class="actual">$12.00</span>
													</div>
													<div class="cart-button">
														<div class="cart">
															<a href="#"><img src="images/cart.png" alt=""/></a>
														</div>
														<button class="button"><span>Details</span></button>
													<div class="clear"></div>
												</div>
											</div>
								</div><div class="clear"></div>
									</div><div class="clear"></div>
								</div>
						</div>
				</div>
		</div>
		<div class="header-para">
				<div class="categories">
						<div class="list-categories">
							<div class="first-list">
								<div class="div_2"><a href="">Cars</a></div>
								<div class="div_img">
									<img src="images/car1.jpg" alt="Cars" title="Cars" width="60" height="39">
								</div><div class="clear"></div>
							</div>
							<div class="first-list">
								<div class="div_2"><a href="">Rental</a></div>
								<div class="div_img">
									<img src="images/car2.jpg" alt="Cars" title="Cars" width="60" height="39">
								</div><div class="clear"></div>
							</div>
							<div class="first-list">
								<div class="div_2"><a href="">Banking</a></div>
								<div class="div_img">
									<img src="images/car3.jpg" alt="Cars" title="Cars" width="60" height="39">
								</div><div class="clear"></div>
							</div>
							<div class="first-list">
								<div class="div_2"><a href="">Trucks</a></div>
								<div class="div_img">
									<img src="images/car4.jpg" alt="Cars" title="Cars" width="60" height="39">
								</div><div class="clear"></div>
							</div>
				</div>
				<div class="box"> 
							<div class="box-heading"><h1><a href="#">Cart:&nbsp;</a></h1></div>
							 <div class="box-content">
							Now in your cart&nbsp;<strong> 0 items</strong>
							</div>	
				</div>
				<div class="box-title">
					<h1><span class="title-icon"></span><a href="">Branches</a></h1>
				</div>
				<div class="section group example">
					<div class="col_1_of_2 span_1_of_2">
					  <img src="images/pic21.jpg" alt=""/>
					   <img src="images/pic24.jpg" alt=""/>
					   <img src="images/pic25.jpg" alt=""/>
					   <img src="images/pic27.jpg" alt=""/>
	 				</div>
					<div class="col_1_of_2 span_1_of_2">
						 <img src="images/pic22.jpg" alt=""/>
					  	<img src="images/pic23.jpg" alt=""/>
					  	<img src="images/pic26.jpg" alt=""/>
					  	<img src="images/pic28.jpg" alt=""/>
					  </div><div class="clear"></div>
		   		 </div>
				<div class="clear"></div>
				</div>
	</div>
		<div class="clear"></div>
		<div class="footer-bottom">
			<div class="copy">
				<p>All rights Reserved | Design by <a href="http://w3layouts.com">W3Layouts</a></p>
			</div>
		</div>
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>

    	
    	
            